directories:
  output: dist
  buildResources: assets
files:
  - filter:
      - build/**/*
      - build/**/*
      - node_modules/**/*
extraMetadata:
  main: build/electron.js
appId: com.hb-dex.HB-WALLET-DESKTOP
productName: HB-WALLET-DESKTOP
copyright: 'Copyright © 2019 ${author}'
mac:
  target:
    - dmg
    - zip
  category: public.app-category.reference
extends: react-cra
electronVersion: 6.0.4
